name: Android CI

on:
  push:
    branches: 
      - master
    tags: 
      - '*'
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        
    - name: Fetch tags
      run: git fetch origin 'refs/tags/*:refs/tags/*'
      
    - name: Lint
      run: ./gradlew lifecyklelog:lint
      
    - name: Test
      run: ./gradlew lifecyklelog:test
      
    - name: Generate test report
      run: ./gradlew lifecyklelog:jacocoTestReport
      
    - name: Detekt
      run: ./gradlew detekt
      
    - name: ktlint
      run: ./gradlew ktlintCheck
      
    - name: Codecov
      uses: codecov/codecov-action@v1.0.7
      
    - name: Set env
      if: startsWith(github.ref, 'refs/tags/*')
      run: echo ::set-env name=RELEASE_VERSION::${GITHUB_REF#refs/*/}
    
    - name: Deploy
      if: startsWith(github.ref, 'refs/tags/*')
      run: ./gradlew bintrayUpload -PbintrayUser=${{ BINTRAY_USER_ID }} -PbintrayKey=${{ BINTRAY_API_KEY }} -PpublishVersion=${{ RELEASE_VERSION }} -PdryRun=true
      
