name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  release:
    types: [ published ]

jobs:
  test:
   runs-on: ubuntu-latest
   steps:
    - uses: actions/checkout@v2.4.0
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: 11
    - name: run testDebugUnitTest
      run: ./gradlew testDebugUnitTest
    - name: run jacocoTestReport
      run: ./gradlew jacocoTestReport
    - uses: codecov/codecov-action@v2.1.0
    - name: upload test results
      uses: actions/upload-artifact@v2
      with:
        name: tests
        path: lifecyklelog/build/reports/
    - name: upload test xml
      uses: actions/upload-artifact@v2
      with:
        name: test_xml
        path: lifecyklelog/build/test-results/

  analyze:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.4.0
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: 11
    - name: run ktlintCheck
      run: ./gradlew ktlintCheck
    - name: run lintDebug
      run: ./gradlew lintDebug
    - name: upload lint results
      uses: actions/upload-artifact@v2
      with:
        name: lint
        path: lifecyklelog/build/reports/
    - name: run detekt
      run: ./gradlew detekt
    - name: upload detekt results
      uses: actions/upload-artifact@v2
      with:
        name: detekt
        path: build/reports/

  danger:
    needs: [test, analyze]
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.4.0
      with:
        fetch-depth: 100
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: 11
    - uses: actions/setup-ruby@v1.1.3
      with:
        ruby-version: '2.6'
    - name: install bundler 2.1.2
      run: gem install bundler:2.1.2
    - uses: actions/cache@v2.1.7
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('Gemfile') }}
        restore-keys: |
          ${{ runner.os }}-gems-
    - name: download lint results
      uses: actions/download-artifact@v2
      with:
        name: lint
        path: lifecyklelog/build/reports/
    - name: download detekt results
      uses: actions/download-artifact@v2
      with:
        name: detekt
        path: build/reports/
    - name: download test results
      uses: actions/download-artifact@v2
      with:
        name: test_xml
        path: lifecyklelog/build/test-results/
    - uses: MeilCli/danger-action@v5.4.14
      if: github.event_name == 'pull_request'
      with:
        plugins_file: 'Gemfile'
        install_path: 'vendor/bundle'
        danger_file: 'Dangerfile'
        danger_id: 'danger-ci'
      env:
        DANGER_GITHUB_API_TOKEN: ${{ secrets.DANGER_API_TOKEN }}

  deploy:
    needs: [test, analyze]
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.4.0
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: 11
    - name: Fetch tags
      run: git fetch origin 'refs/tags/*:refs/tags/*'
    - name: run assemble
      run: ./gradlew assemble
    - name: Set env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: Deploy
      run: ./gradlew deploy -PbintrayUser=${{ secrets.BINTRAY_USER_ID }} -PbintrayKey=${{ secrets.BINTRAY_API_KEY }} -PpublishVersion=$RELEASE_VERSION
