name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
   runs-on: ubuntu-latest
   steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1.4.1
      with:
        java-version: 1.8
    - name: run testDebugUnitTest
      run: ./gradlew testDebugUnitTest
    - name: run jacocoTestReport
      run: ./gradlew jacocoTestReport
    - uses: codecov/codecov-action@v1.0.12
    - name: upload test results
      uses: actions/upload-artifact@v2
      with:
        name: tests
        path: app/build/reports/
    - name: upload test xml
      uses: actions/upload-artifact@v2
      with:
        name: test_xml
        path: app/build/test-results/
