name: Android CI

on:
  push:
    branches: [ master ]
    tags: [ '*' ]
  pull_request:
    branches: [ master ]

jobs:
  test:
   runs-on: ubuntu-latest
   steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1.4.1
      with:
        java-version: 1.8
    - name: run testDebugUnitTest
      run: ./gradlew testDebugUnitTest
    - name: run jacocoTestReport
      run: ./gradlew jacocoTestReport
    - uses: codecov/codecov-action@v1.0.12
    - name: upload test results
      uses: actions/upload-artifact@v2
      with:
        name: tests
        path: lifecyklelog/build/reports/
    - name: upload test xml
      uses: actions/upload-artifact@v2
      with:
        name: test_xml
        path: lifecyklelog/build/test-results/

  analyze:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1.4.1
      with:
        java-version: 1.8
    - name: run ktlintCheck
      run: ./gradlew ktlintCheck
    - name: run lintDebug
      run: ./gradlew lintDebug
    - name: upload lint results
      uses: actions/upload-artifact@v2
      with:
        name: lint
        path: lifecyklelog/build/reports/
    - name: run detekt
      run: ./gradlew detekt
    - name: upload detekt results
      uses: actions/upload-artifact@v2
      with:
        name: detekt
        path: build/reports/

  danger:
    needs: [test, analyze]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 100
    - name: set up JDK 1.8
      uses: actions/setup-java@v1.4.1
      with:
        java-version: 1.8
    - uses: actions/setup-ruby@v1.1.1
      with:
        ruby-version: '2.6'
    - name: install bundler 2.1.2
      run: gem install bundler:2.1.2
    - uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('Gemfile') }}
        restore-keys: |
          ${{ runner.os }}-gems-
    - name: download lint results
      uses: actions/download-artifact@v2
      with:
        name: lint
        path: lifecyklelog/build/reports/
    - name: download detekt results
      uses: actions/download-artifact@v2
      with:
        name: detekt
        path: build/reports/
    - name: download test results
      uses: actions/download-artifact@v2
      with:
        name: test_xml
        path: lifecyklelog/build/test-results/
    - uses: MeilCli/danger-action@v5.0.0
      if: github.event_name == 'pull_request'
      with:
        plugins_file: 'Gemfile'
        install_path: 'vendor/bundle'
        danger_file: 'Dangerfile'
        danger_id: 'danger-ci'
      env:
        DANGER_GITHUB_API_TOKEN: ${{ secrets.DANGER_API_TOKEN }}

  deploy:
    if: startsWith(github.ref, 'refs/tags/*')
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1.4.1
      with:
        java-version: 1.8
    - name: Fetch tags
      run: git fetch origin 'refs/tags/*:refs/tags/*'
    - name: run assembleDebug
      run: ./gradlew assembleDebug
    - name: Set env
      run: echo ::set-env name=RELEASE_VERSION::${GITHUB_REF#refs/*/}
    - name: Deploy
      run: ./gradlew bintrayUpload -PbintrayUser=${{ secrets.BINTRAY_USER_ID }} -PbintrayKey=${{ secrets.BINTRAY_API_KEY }} -PpublishVersion=${{ env.RELEASE_VERSION }} -PdryRun=false
